version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "solidarity-backend"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-yez4rhx2sihv"
s3_prefix = "solidarity-backend"
region = "eu-central-1"
profile = "private"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

